"""initial schema

Revision ID: 20260808_01
Revises:
Create Date: 2026-08-08 14:47:35.369454
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260808_01"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "daily_data_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("resource", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "day", "resource"),
    )
    op.create_index(
        op.f("ix_daily_data_statuses_day"), "daily_data_statuses", ["day"], unique=False
    )
    op.create_index(
        op.f("ix_daily_data_statuses_user_id"), "daily_data_statuses", ["user_id"], unique=False
    )
    op.create_table(
        "daily_fitness",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("vo2max", sa.Float(), nullable=True),
        sa.Column("training_status", sa.String(length=50), nullable=True),
        sa.Column("training_load", sa.Float(), nullable=True),
        sa.Column("acute_load", sa.Float(), nullable=True),
        sa.Column("chronic_load", sa.Float(), nullable=True),
        sa.Column("load_ratio", sa.Float(), nullable=True),
        sa.Column("garmin_training_readiness_score", sa.Integer(), nullable=True),
        sa.Column("garmin_training_readiness_level", sa.String(length=50), nullable=True),
        sa.Column("recovery_time_minutes", sa.Integer(), nullable=True),
        sa.Column("endurance_score", sa.Float(), nullable=True),
        sa.Column("hill_score", sa.Float(), nullable=True),
        sa.Column("fitness_age", sa.Float(), nullable=True),
        sa.Column("lactate_threshold_hr", sa.Integer(), nullable=True),
        sa.Column("lactate_threshold_speed_mps", sa.Float(), nullable=True),
        sa.Column("running_ftp_watts", sa.Float(), nullable=True),
        sa.Column("cycling_ftp_watts", sa.Float(), nullable=True),
        sa.Column("race_prediction_5k_seconds", sa.Integer(), nullable=True),
        sa.Column("race_prediction_10k_seconds", sa.Integer(), nullable=True),
        sa.Column("race_prediction_half_seconds", sa.Integer(), nullable=True),
        sa.Column("race_prediction_marathon_seconds", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "day"),
    )
    op.create_index(op.f("ix_daily_fitness_day"), "daily_fitness", ["day"], unique=False)
    op.create_index(op.f("ix_daily_fitness_user_id"), "daily_fitness", ["user_id"], unique=False)
    op.create_table(
        "daily_health",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("sleep_seconds", sa.Integer(), nullable=True),
        sa.Column("sleep_score", sa.Integer(), nullable=True),
        sa.Column("sleep_score_duration", sa.Integer(), nullable=True),
        sa.Column("sleep_score_stress", sa.Integer(), nullable=True),
        sa.Column("sleep_score_awake_count", sa.Integer(), nullable=True),
        sa.Column("sleep_score_rem_percentage", sa.Integer(), nullable=True),
        sa.Column("sleep_score_restlessness", sa.Integer(), nullable=True),
        sa.Column("sleep_score_light_percentage", sa.Integer(), nullable=True),
        sa.Column("sleep_score_deep_percentage", sa.Integer(), nullable=True),
        sa.Column("sleep_start_at", sa.DateTime(), nullable=True),
        sa.Column("sleep_end_at", sa.DateTime(), nullable=True),
        sa.Column("deep_sleep_seconds", sa.Integer(), nullable=True),
        sa.Column("light_sleep_seconds", sa.Integer(), nullable=True),
        sa.Column("rem_sleep_seconds", sa.Integer(), nullable=True),
        sa.Column("awake_sleep_seconds", sa.Integer(), nullable=True),
        sa.Column("nap_seconds", sa.Integer(), nullable=True),
        sa.Column("sleep_need_seconds", sa.Integer(), nullable=True),
        sa.Column("sleep_need_baseline_seconds", sa.Integer(), nullable=True),
        sa.Column("next_sleep_need_seconds", sa.Integer(), nullable=True),
        sa.Column("sleep_average_hr", sa.Float(), nullable=True),
        sa.Column("sleep_average_stress", sa.Float(), nullable=True),
        sa.Column("sleep_body_battery_change", sa.Integer(), nullable=True),
        sa.Column("resting_hr", sa.Integer(), nullable=True),
        sa.Column("min_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("hrv_average", sa.Float(), nullable=True),
        sa.Column("hrv_weekly_average", sa.Float(), nullable=True),
        sa.Column("hrv_five_min_high", sa.Float(), nullable=True),
        sa.Column("hrv_status", sa.String(length=30), nullable=True),
        sa.Column("hrv_baseline_low", sa.Float(), nullable=True),
        sa.Column("hrv_baseline_balanced_low", sa.Float(), nullable=True),
        sa.Column("hrv_baseline_balanced_high", sa.Float(), nullable=True),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("total_calories", sa.Integer(), nullable=True),
        sa.Column("active_calories", sa.Integer(), nullable=True),
        sa.Column("stress_average", sa.Integer(), nullable=True),
        sa.Column("stress_max", sa.Integer(), nullable=True),
        sa.Column("body_battery_high", sa.Integer(), nullable=True),
        sa.Column("body_battery_low", sa.Integer(), nullable=True),
        sa.Column("body_battery_charged", sa.Integer(), nullable=True),
        sa.Column("body_battery_drained", sa.Integer(), nullable=True),
        sa.Column("waking_respiration_average", sa.Float(), nullable=True),
        sa.Column("sleep_respiration_average", sa.Float(), nullable=True),
        sa.Column("spo2_average", sa.Float(), nullable=True),
        sa.Column("sleep_spo2_average", sa.Float(), nullable=True),
        sa.Column("spo2_lowest", sa.Float(), nullable=True),
        sa.Column("moderate_intensity_minutes", sa.Integer(), nullable=True),
        sa.Column("vigorous_intensity_minutes", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "day"),
    )
    op.create_index(op.f("ix_daily_health_day"), "daily_health", ["day"], unique=False)
    op.create_index(op.f("ix_daily_health_user_id"), "daily_health", ["user_id"], unique=False)
    op.create_table(
        "garmin_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("connected_at", sa.DateTime(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("sync_status", sa.String(length=30), nullable=False),
        sa.Column("sync_error", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "garmin_sync_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("resource", sa.String(length=50), nullable=False),
        sa.Column("oldest_synced_date", sa.Date(), nullable=True),
        sa.Column("newest_synced_date", sa.Date(), nullable=True),
        sa.Column("backfill_cursor_date", sa.Date(), nullable=True),
        sa.Column("cursor", sa.String(length=200), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("backfill_complete", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "resource"),
    )
    op.create_index(
        op.f("ix_garmin_sync_states_user_id"), "garmin_sync_states", ["user_id"], unique=False
    )
    op.create_table(
        "oauth_identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "subject"),
    )
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("current_item", sa.Integer(), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("activities_synced", sa.Integer(), nullable=False),
        sa.Column("health_days_synced", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_runs_user_id"), "sync_runs", ["user_id"], unique=False)
    op.create_table(
        "workouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sport", sa.String(length=30), nullable=False),
        sa.Column("scheduled_for", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("garmin_workout_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workouts_scheduled_for"), "workouts", ["scheduled_for"], unique=False)
    op.create_index(op.f("ix_workouts_status"), "workouts", ["status"], unique=False)
    op.create_index(op.f("ix_workouts_user_id"), "workouts", ["user_id"], unique=False)
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("garmin_activity_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("activity_type", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("elapsed_duration_s", sa.Float(), nullable=True),
        sa.Column("moving_duration_s", sa.Float(), nullable=True),
        sa.Column("average_speed_mps", sa.Float(), nullable=True),
        sa.Column("max_speed_mps", sa.Float(), nullable=True),
        sa.Column("min_hr", sa.Integer(), nullable=True),
        sa.Column("average_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("elevation_gain_m", sa.Float(), nullable=True),
        sa.Column("elevation_loss_m", sa.Float(), nullable=True),
        sa.Column("average_cadence", sa.Float(), nullable=True),
        sa.Column("max_cadence", sa.Float(), nullable=True),
        sa.Column("average_power_watts", sa.Float(), nullable=True),
        sa.Column("max_power_watts", sa.Float(), nullable=True),
        sa.Column("normalized_power_watts", sa.Float(), nullable=True),
        sa.Column("aerobic_training_effect", sa.Float(), nullable=True),
        sa.Column("anaerobic_training_effect", sa.Float(), nullable=True),
        sa.Column("training_effect_label", sa.String(length=100), nullable=True),
        sa.Column("exercise_load", sa.Float(), nullable=True),
        sa.Column("vo2max", sa.Float(), nullable=True),
        sa.Column("stride_length_cm", sa.Float(), nullable=True),
        sa.Column("ground_contact_time_ms", sa.Float(), nullable=True),
        sa.Column("vertical_oscillation_cm", sa.Float(), nullable=True),
        sa.Column("vertical_ratio", sa.Float(), nullable=True),
        sa.Column("workout_rpe", sa.Integer(), nullable=True),
        sa.Column("workout_feel", sa.Integer(), nullable=True),
        sa.Column("moderate_intensity_minutes", sa.Integer(), nullable=True),
        sa.Column("vigorous_intensity_minutes", sa.Integer(), nullable=True),
        sa.Column("body_battery_change", sa.Integer(), nullable=True),
        sa.Column("associated_garmin_workout_id", sa.String(length=100), nullable=True),
        sa.Column("workout_id", sa.Integer(), nullable=True),
        sa.Column("raw_file", sa.String(length=500), nullable=True),
        sa.Column("details_file", sa.String(length=500), nullable=True),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(), nullable=True),
        sa.Column("details_complete", sa.Boolean(), nullable=False),
        sa.Column("splits_complete", sa.Boolean(), nullable=False),
        sa.Column("details_synced_at", sa.DateTime(), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "garmin_activity_id"),
    )
    op.create_index(
        op.f("ix_activities_activity_type"), "activities", ["activity_type"], unique=False
    )
    op.create_index(
        op.f("ix_activities_associated_garmin_workout_id"),
        "activities",
        ["associated_garmin_workout_id"],
        unique=False,
    )
    op.create_index(op.f("ix_activities_started_at"), "activities", ["started_at"], unique=False)
    op.create_index(op.f("ix_activities_user_id"), "activities", ["user_id"], unique=False)
    op.create_index(op.f("ix_activities_workout_id"), "activities", ["workout_id"], unique=False)
    op.create_table(
        "garmin_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("garmin_device_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["garmin_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "garmin_device_id"),
    )
    op.create_table(
        "sleep_stages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("daily_health_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["daily_health_id"], ["daily_health.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("daily_health_id", "position"),
    )
    op.create_index(
        op.f("ix_sleep_stages_daily_health_id"), "sleep_stages", ["daily_health_id"], unique=False
    )
    op.create_table(
        "workout_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("step_type", sa.String(length=30), nullable=False),
        sa.Column("duration_type", sa.String(length=30), nullable=False),
        sa.Column("duration_value", sa.Float(), nullable=True),
        sa.Column("target_type", sa.String(length=30), nullable=False),
        sa.Column("target_min", sa.Float(), nullable=True),
        sa.Column("target_max", sa.Float(), nullable=True),
        sa.Column("repeat_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workout_id", "position"),
    )
    op.create_index(
        op.f("ix_workout_steps_workout_id"), "workout_steps", ["workout_id"], unique=False
    )
    op.create_table(
        "activity_exercise_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("set_type", sa.String(length=30), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("repetitions", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("exercise_category", sa.String(length=100), nullable=True),
        sa.Column("exercise_name", sa.String(length=150), nullable=True),
        sa.Column("workout_step_index", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_id", "position"),
    )
    op.create_index(
        op.f("ix_activity_exercise_sets_activity_id"),
        "activity_exercise_sets",
        ["activity_id"],
        unique=False,
    )
    op.create_table(
        "activity_splits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("split_type", sa.String(length=30), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("intensity_type", sa.String(length=30), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("elapsed_duration_s", sa.Float(), nullable=True),
        sa.Column("moving_duration_s", sa.Float(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("elevation_gain_m", sa.Float(), nullable=True),
        sa.Column("elevation_loss_m", sa.Float(), nullable=True),
        sa.Column("average_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("average_speed_mps", sa.Float(), nullable=True),
        sa.Column("max_speed_mps", sa.Float(), nullable=True),
        sa.Column("average_cadence", sa.Float(), nullable=True),
        sa.Column("max_cadence", sa.Float(), nullable=True),
        sa.Column("average_power_watts", sa.Float(), nullable=True),
        sa.Column("max_power_watts", sa.Float(), nullable=True),
        sa.Column("normalized_power_watts", sa.Float(), nullable=True),
        sa.Column("stride_length_cm", sa.Float(), nullable=True),
        sa.Column("ground_contact_time_ms", sa.Float(), nullable=True),
        sa.Column("vertical_oscillation_cm", sa.Float(), nullable=True),
        sa.Column("vertical_ratio", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_id", "split_type", "position"),
    )
    op.create_index(
        op.f("ix_activity_splits_activity_id"), "activity_splits", ["activity_id"], unique=False
    )
    op.create_table(
        "activity_zones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("zone_type", sa.String(length=20), nullable=False),
        sa.Column("zone_number", sa.Integer(), nullable=False),
        sa.Column("low_boundary", sa.Float(), nullable=True),
        sa.Column("seconds", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_id", "zone_type", "zone_number"),
    )
    op.create_index(
        op.f("ix_activity_zones_activity_id"), "activity_zones", ["activity_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_zones_activity_id"), table_name="activity_zones")
    op.drop_table("activity_zones")
    op.drop_index(op.f("ix_activity_splits_activity_id"), table_name="activity_splits")
    op.drop_table("activity_splits")
    op.drop_index(
        op.f("ix_activity_exercise_sets_activity_id"), table_name="activity_exercise_sets"
    )
    op.drop_table("activity_exercise_sets")
    op.drop_index(op.f("ix_workout_steps_workout_id"), table_name="workout_steps")
    op.drop_table("workout_steps")
    op.drop_index(op.f("ix_sleep_stages_daily_health_id"), table_name="sleep_stages")
    op.drop_table("sleep_stages")
    op.drop_table("garmin_devices")
    op.drop_index(op.f("ix_activities_workout_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_user_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_started_at"), table_name="activities")
    op.drop_index(op.f("ix_activities_associated_garmin_workout_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_activity_type"), table_name="activities")
    op.drop_table("activities")
    op.drop_index(op.f("ix_workouts_user_id"), table_name="workouts")
    op.drop_index(op.f("ix_workouts_status"), table_name="workouts")
    op.drop_index(op.f("ix_workouts_scheduled_for"), table_name="workouts")
    op.drop_table("workouts")
    op.drop_index(op.f("ix_sync_runs_user_id"), table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_table("oauth_identities")
    op.drop_index(op.f("ix_garmin_sync_states_user_id"), table_name="garmin_sync_states")
    op.drop_table("garmin_sync_states")
    op.drop_table("garmin_accounts")
    op.drop_index(op.f("ix_daily_health_user_id"), table_name="daily_health")
    op.drop_index(op.f("ix_daily_health_day"), table_name="daily_health")
    op.drop_table("daily_health")
    op.drop_index(op.f("ix_daily_fitness_user_id"), table_name="daily_fitness")
    op.drop_index(op.f("ix_daily_fitness_day"), table_name="daily_fitness")
    op.drop_table("daily_fitness")
    op.drop_index(op.f("ix_daily_data_statuses_user_id"), table_name="daily_data_statuses")
    op.drop_index(op.f("ix_daily_data_statuses_day"), table_name="daily_data_statuses")
    op.drop_table("daily_data_statuses")
    op.drop_table("users")
    # ### end Alembic commands ###
